FROM debian:stable
RUN apt-get update && apt-get install -y --no-install-recommends \
    coreutils \
    curl \
    make \
    openssl \
    python \
    sed \
    && rm -Rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    && rm -Rf /var/lib/apt/lists/*

ARG VERSION=latest

ADD acme-wrapper.tar.bz2 /root
WORKDIR /root/acme-wrapper_$VERSION
RUN make
RUN make install

WORKDIR /
RUN rm -rf /root/acme-wrapper_$VERSION


COPY --chown=root:root mock_acme_tiny.py /opt/acme_tiny.py
RUN chmod 0755 /opt/acme_tiny.py
RUN ln -nf /opt/acme_tiny.py /opt/acme-wrapper/libexec/acme-tiny/acme_tiny.py
