#!/bin/bash

mydir="$(dirname "$0")"
. ${mydir}/lib/sysexits.sh
. ${mydir}/lib/common.sh
. ${mydir}/etc/config.sh

printhelp() {
    echoerr "$0 [OPTIONS]"
    echoerr ""
    echoerr "generate a new letsencrypt account rsa key-pair"
    echoerr ""
    echoerr "OPTIONS:"
    echoerr "  --help display this help and exit"
    echoerr "  "
}

parse_cmdline() {
    # no command line options beside --help
    [[ "$#" -ne 0 ]] && {
        printhelp
        exit $EX_USAGE
    }
}

parse_cmdline "$@"


datestr="$(date +%Y-%m-%d)"
keyfile="${mydir}/${datestr}_letsencrypt-account_key.pem"
pubfile="${mydir}/${datestr}_letsencrypt-account_pub.pem"

openssl genrsa "$RSA_KEY_BITS" > "${keyfile}"
chmod go-rwx "${keyfile}"
ln -snf "${keyfile}" "${mydir}/account.key"

openssl rsa -in "${keyfile}" -pubout > "${pubfile}"
ln -snf "${pubfile}" "${mydir}/account.pub"
