#!/bin/bash

[[ -n "$1" ]] || {
    echo "hostname as first parameter"
    exit 0
}

name="$(date +%Y-%m-%d)_letsencrypt_$1"

openssl genrsa -out "private/${name}_key.pem" 4096
chmod go-rwx "private/${name}_key.pem"

