#!/bin/bash

[[ -n "$1" ]] || {
    echo "hostname as first parameter"
    exit 0
}

hostname="$1"
basedomain="$(sed -re 's/(.*\.)?([^.]+\.[^.]+)/\2/' <<<"${hostname}")"
name="$(date +%Y-%m-%d)_letsencrypt_$1"

python acme-tiny/acme_tiny.py --account-key ./account.key --csr "public/${name}_csr.pem" --acme-dir /var/www/acme-challenge/ > "public/${name}_crt.pem"
