#!/bin/bash

[[ -n "$1" ]] || {
    echo "hostname as first parameter"
    exit 0
}

hostname="$1"
basedomain="$(sed -re 's/(.*\.)?([^.]+\.[^.]+)/\2/' <<<"${hostname}")"
name="$(date +%Y-%m-%d)_letsencrypt_$1"

python letsencrypt-nosudo/sign_csr.py -p user.pub -k user.key --autosign \
    --file-dir /var/www/html -e hostmaster@${basedomain} \
    -f "public/${name}_csr.pem" > "public/${name}_crt.pem"

