#!/bin/sh
set -e

#DEBHELPER#

case $1 in
    remove)
        rm -rf /var/opt/acme-wrapper/home
        rm -rf /var/opt/acme-wrapper/www
        ;;
    purge)
        rm -rf /var/opt/acme-wrapper/database
        rm -rf /var/opt/acme-wrapper/letsencrypt-account
        rm -rf /var/opt/acme-wrapper/spool
        ;;
esac

rmdir /var/opt/acme-wrapper || true
